name: check-llvm20

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout llvm-autojit
      uses: actions/checkout@v4
    - name: Pull docker image
      run: docker pull weliveindetail/ubuntu-llvm20:22.04
    - name: Run regression tests
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace/llvm-autojit \
          -w /workspace \
          weliveindetail/ubuntu-llvm20:22.04 \
          ./llvm-autojit/benchmark/ubuntu2204/docker-tests.sh
    - name: Build sample projects
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace/llvm-autojit \
          -w /workspace \
          weliveindetail/ubuntu-llvm20:22.04 \
          ./llvm-autojit/benchmark/ubuntu2204/docker-samples.sh
