name: Ubuntu 22.04

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-llvm20:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout llvm-autojit
      uses: actions/checkout@v4
    - name: Pull docker image
      run: docker pull weliveindetail/ubuntu-llvm20:22.04
    - name: Run regression tests against Ubuntu LLVM 20.1.8
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace/llvm-autojit \
          -w /workspace \
          weliveindetail/ubuntu-llvm20:22.04 \
          /workspace/llvm-autojit/benchmark/ubuntu2204/docker-tests.sh

  check-llvm21:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout llvm-autojit
      uses: actions/checkout@v4
    - name: Pull docker image
      run: docker pull weliveindetail/ubuntu-llvm21:22.04
    - name: Run regression tests against Ubuntu LLVM 21.1.5
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace/llvm-autojit \
          -w /workspace \
          weliveindetail/ubuntu-llvm21:22.04 \
          /workspace/llvm-autojit/benchmark/ubuntu2204/docker-tests.sh
    - name: Build sample projects with shared library
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace/llvm-autojit \
          -w /workspace \
          weliveindetail/ubuntu-llvm21:22.04 \
          /workspace/llvm-autojit/benchmark/ubuntu2204/docker-samples-shlib.sh
    - name: Build sample projects with static stub and autojitd
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace/llvm-autojit \
          -w /workspace \
          weliveindetail/ubuntu-llvm21:22.04 \
          /workspace/llvm-autojit/benchmark/ubuntu2204/docker-samples-autojitd.sh
